[package]
name = "todo_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28.0"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
chrono = {version = "0.4.38", features = ["serde"]}
indoc = "2.0.5"
itertools = "0.13.0"